version: '3.9'
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db_server
      - redis
    volumes:
      - ./dedicated_billing:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/docker-vars.ini
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx.vh.default.conf:/etc/nginx/conf.d/default.conf
      - ./config/sites-available:/etc/nginx/sites-available
    ports:
      - 8081:80
    depends_on:
      - redis
      - db_server
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis.conf
  db_server:
    image: postgres
    ports:
    - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dedicated_billing
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres